apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uiplugins.catalog.cattle.io
spec:
  group: catalog.cattle.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                version:
                  type: string
                description:
                  type: string
                icon:
                  type: string
  scope: Namespaced
  names:
    plural: uiplugins
    singular: uiplugins
    kind: UIPlugin
    shortNames:
    - uip